### ISSUE TITLE
Overleaf - Fatal error occurred, no output PDF file produced!

### ISSUE THREAD

**Issue by Tuginho** [latextemplates/scientific-thesis-template#77]
I have created the project as indicated but still getting this error:

/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload.sty:49:
==> Fata
l error occurred, no output PDF file produced!

**Comment by koppor** [comment]
Quick fix: use pdflatex. There should be a setting somewhere.

Am 15.03.2018 21:08 schrieb "Tugay Yentur" <notifications@github.com>:

I have created the project as indicated but still getting this error:

/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload.sty:49:
==> Fata
l error occurred, no output PDF file produced!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/latextemplates/scientific-thesis-template/issues/77>,
or mute the thread

**Comment by Tuginho** [comment]
Thanks for your fast reply. It worked with your hint and after I set in the config compat to 1.14.

**Comment by koppor** [comment]
Thank you. I updated the howto at http://latextemplates.github.io/scientific-thesis-template/overleaf.html and set pgfplot compatibility level to 1.14 (see https://github.com/latextemplates/scientific-thesis-template/commit/11a4ee03732b8eefd264f7e7ddb65ab36bd499be).

**Comment by Emsterio** [comment]
> Quick fix: use pdflatex. There should be a setting somewhere.

How do I do that?
