### ISSUE TITLE
.editorconfig enforcing 2 spaces as indentation

### ISSUE THREAD

**Issue by SpechtMagnus** [latextemplates/scientific-thesis-template#90]
The .editorconfig in this repository forces 2 spaces as indentation for all filetypes except .yaml. This is a very annoying and hardly spottable bug.

I would advise to completely get rid of the .editorconfig file.

**Comment by koppor** [comment]
Could you elaborate more on "annoying"?

Quoting https://editorconfig.org/

> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.

It helps much to maintain this template and ensure consistent formatting. I required 4 spaces in YAML, because of https://github.com/latextemplates/scientific-thesis-template/blob/master/localSettings.yaml.

In my experience, for newcomers, it is easy, if there is a consistent code style in projects. There are articles around justifying that. For instance https://www.smashingmagazine.com/2012/10/why-coding-style-matters/. It is also teached (used to be teached?) in the software engineering studies at USTUTT.

I assume, you added a `.yaml` file to the repository and had issues there? Then, we could try whether a recent latexindent version has issues with files.

I can also change the `.editorconfig` to deal with `*.tex`, `*.bib`, `*.sty`?, `*.md`? only.

**Comment by SpechtMagnus** [comment]
> I can also change the .editorconfig to deal with *.tex, *.bib, *.sty?, *.md? only.
This would be a good solution. My problem mainly concerns other file extensions such as .java and .cpp containing source code that I want to add to my paper.

**Comment by koppor** [comment]
Fixed in https://github.com/latextemplates/scientific-thesis-template/commit/6d667ac22559096c24f06228fd69ac58bb0c82ae.

**Comment by koppor** [comment]
I released 3.0.0-beta.3 (see https://github.com/latextemplates/scientific-thesis-template/releases). Please try that.

This is close to a release. I, however, will check the recommendations regarding the table of contents at [Technische Berichte - Verständlich gliedern, gut gestalten, überzeugend vortragen](https://link.springer.com/book/10.1007%2F978-3-8348-8317-9).

Otherwise this template won't receive many updates.

Meanwhile, I'm working on https://github.com/latextemplates/latex-template-generator. Help extremely welcome!
